language: node_js

node_js:
 - node
 - 4

sudo: false

install:
 - npm install
 - typings install

script:
 - npm run build
 - npm test

before_deploy:
 - npm run typedoc
deploy:
  skip_cleanup: true
  provider: surge
  project: ./typedoc/
  domain: cli-highlight.surge.sh
