language: node_js

node_js:
 - 6

sudo: false

env:
  global:
   - CODECOV_TOKEN=76be2746-185f-49c1-a302-ed592d765a67

install:
 - npm install
 - typings install

script:
 - npm run build
 - npm run cover

after_success:
 - 'nyc report --reporter=lcov > coverage.lcov && codecov'

before_deploy:
 - npm run typedoc
deploy:
  skip_cleanup: true
  provider: surge
  project: ./typedoc/
  domain: merkel.surge.sh
