language: node_js

node_js:
  - '8'

cache:
  directories:
    - ~/.npm

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - MERKEL_DB=postgres://postgres@localhost:5432/merkel_test

before_install:
  - npm install -g npm@6.0.0

install:
  - npm ci

script:
  - createdb merkel_test
  - git config --global user.email 'whatever@whatever.com'
  - git config --global user.name 'whatever'
  - npm run build
  - npm run cover -- --colors
  - nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json

jobs:
  include:
    - stage: test
    - stage: release
      script:
        - npm run build
        - npm run semantic-release
      before_deploy:
        - npm run typedoc
      deploy:
        skip_cleanup: true
        provider: surge
        project: ./typedoc/
        domain: merkel.surge.sh

stages:
  - test
  - name: release
    if: branch = master AND type = push AND fork = false

branches:
  only:
    - master
    - /^greenkeeper.*$/
