language: node_js

node_js:
 - 8

sudo: false

services:
 - postgresql

env:
  global:
   - CODECOV_TOKEN=76be2746-185f-49c1-a302-ed592d765a67
   - MERKEL_DB=postgres://postgres@localhost:5432/merkel_test

install:
 - npm install
 - typings install

before_script:
 - psql -c 'CREATE DATABASE merkel_test;' -U postgres
 - git config --global user.email 'whatever@whatever.com'
 - git config --global user.name 'whatever'

script:
 - npm run build
 - npm run cover

after_success:
 - 'nyc report --reporter=lcov && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info'

before_deploy:
 - npm run typedoc
deploy:
  skip_cleanup: true
  provider: surge
  project: ./typedoc/
  domain: merkel.surge.sh
