version: '{build}'

platform:
  - x64

services:
  - postgresql

shallow_clone: true

environment:
  MERKEL_DB: postgres://postgres:Password12!@localhost:5432/merkel_test
  PGPASSWORD: Password12!

install:
  - ps: Install-Product node $env:NODE_VERSION x64
  - npm install

build_script:
  - npm run build

before_test:
  - '"C:\Program Files\PostgreSQL\9.3\bin\psql" -c "CREATE DATABASE merkel_test;" -U postgres'
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

test_script:
  - npm test
