version: '{build}'

image: Visual Studio 2017
clone_depth: 1
skip_branch_with_pr: true
skip_tags: true

cache:
  - '%APPDATA%\npm-cache'

services:
  - postgresql96

environment:
  NODE_VERSION: '8'
  MERKEL_DB: postgres://postgres:Password12!@localhost:5432/merkel_test
  PGUSER: postgres
  PGPASSWORD: Password12!

install:
  - ps: Install-Product node $env:NODE_VERSION x64
  - npm install

build_script:
  - npm run build

before_test:
  - SET PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - createdb merkel_test
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

test_script:
  # Coverage doesn't work because of https://github.com/tapjs/spawn-wrap/issues/69
  - npm test -- --colors

after_test:
  - ps: |
      node_modules\.bin\nyc report --reporter=json
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f coverage\coverage-final.info
